name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Run Linter
      run: |
        pip install pylint
        pylint main.py || true  # Ensures the build doesn't fail due to linter warnings

    - name: Run Script
      run: python hello.py

    - name: Create artefact zip
      run: zip artefact.zip main.py

    - name: Upload artefact
      uses: actions/upload-artifact@v2
      with:
        name: artefact
        path: artefact.zip
